client_config_backend: file
client_config:
    client_id: 976414764845-7kpsemcnslls2n58n0mdnu6ijrtqadpo.apps.googleusercontent.com
    client_secret: Aaq3h3Obee2nLQB9Tjuog_Ey

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install